[platformio]
default_envs = cardputer

[env:cardputer]
platform = espressif32
board = m5stack-cores3
framework = arduino
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified
    m5stack/M5Cardputer
lib_extra_dirs = ${PROJECT_DIR}/../lib
